# Generated by Django 5.0.4 on 2024-05-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.transaction'),
        ),
    ]
