# Generated by Django 5.0.4 on 2024-05-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_transaction_original_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
