# Generated by Django 5.0.4 on 2024-05-24 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_transaction_original_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='original_transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='budget.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.transaction'),
        ),
    ]
